name: "traceparent-plugin"
version: "v1.0.0"
type: "middleware"
import: "github.com/rafal-slowik/traceparent-plugin"
displayName: "Traceparent Generator Plugin"
summary: "A plugin for injecting traceparent headers"
description: "Generates a otel traceparent header using Azure Application Gateway's transaction ID as trace-id and random span-id."
author: "RAFAL SLOWIK"
testData: {}